src/document/html/parser/forms.c
src/viewer/text/form.c
src/viewer/text/link.c

Insert "[_" and "_]" as part of the form link, and
include it as part of the link.

Make select forms look more like other forms.

---

src/network/ssl/ssl.c

I was not able to test this patch, as I failed tó use client certs even with OpenSSL

SSL authentication using client certs

---

src/ecmascript/spidermonkey/heartbeat.c

Build failed because hearbeat.c uses SIGVTALRM

Add signal.h to heartbeat,c includes

---

INSTALL
doc/man/man1/elinks.1.in
doc/remote.txt

Looks like I forgot to add the new "reload()" remote command to the documentation. Here it is.

document '-remote reload()'

---

contrib/debian/watch

Update URL in contrib/debian/watch
I would rather if contrib/debian is removed altogether

Update watch file

---

src/terminal/kbd.c

do not enable mouse from keyboard initialization if mouse is disabled

---

src/config/options.c

Configure st automatically since it is [very popular](https://www.distrotube.com/phpbb/viewtopic.php?t=6).

[config] Recognize st

---

src/ecmascript/spidermonkey.c
src/ecmascript/spidermonkey/Makefile
src/ecmascript/spidermonkey/console.c
src/ecmascript/spidermonkey/console.h
test/ecmascript/console_log.html

Hello rkd77,
this is one more try to provide console log standalone. It is compilable. I added all the comments You have had except the stand-alone option for the console.log location. That could be implemented once we're done with these.
Let me know if this PR is acceptable.
Thank You

SpiderMonkey Update v0.1.a - Console Log

---

configure.ac
src/ecmascript/ecmascript.c
src/ecmascript/ecmascript.h
src/ecmascript/spidermonkey.c
src/ecmascript/spidermonkey/Makefile
src/ecmascript/spidermonkey/localstorage-db.c
src/ecmascript/spidermonkey/localstorage-db.h
src/ecmascript/spidermonkey/localstorage.c
src/ecmascript/spidermonkey/localstorage.h
src/ecmascript/spidermonkey/meson.build
test/ecmascript/local_storage.html

Hello rdk77,
this is the Spidermonkey Local Storage patch. I did change the configure.ac and added sqlite3. But I'm unsure whether this is the correct way on how to do it.
I did change the meson in ecmascript / spidermonkey but probably something has to be changed elsewhere to add sqlite and I'm unsure where.
I tried to add the return values for sqlite function but checking for each seems quite overkill for me. Right now I suppose it's just operation that is quite certain to be completed since the sqlite file is sucesfully opened.
The sqlite database name is generated once and it's in local_storage_filename.
This patch includes the javascript warning patch. From this point of view the:
https://github.com/rkd77/elinks/pull/96
Is now redundant.
It did compile and the test is provided.
Thank …

[smjs] Spidermonkey Local Storage

---

src/ecmascript/spidermonkey.c

Hello,
this is PR to fix this:
https://github.com/rkd77/elinks/issues/95
Since mozjs52 the exception handling is different and the error has to be catched right after evaluation.
Feel free to test || modify.
There is a weird behavior of the error reporting that gives the first report as on 0 line and undefined.
This is handled and the second error with the correct line number and error message is catched and displayed.
Thank You

[smjs] fixed spidermonkey error reporting for mozjs52

---

AUTHORS
po/sr.po

This PR updates the Serbian translation (last updated in 2005) and my email address in AUTHORS.

Update Serbian translation

---

build.sh
test.sh
test/remote.sh

Hello rkd77,
I'm offering elinks remote control tests revision (testremote). I did add test.sh and changed the build.sh to call it.
Thank You and best regardards

[ tests ] remote control test revision

---

.gitignore
build.sh
test.sh
test/server/gen.sh
test/server/https.py

Hello rkd77,
this commit adds https server for testing, snake oil certificate generate script, new options for test.sh, adds aarch64 to build menu.
Thank You very much for Your work.

[ build ] added aarch64, testing https server

---

build.sh
docker/win64/Dockerfile
docker/win64/build.sh
docker/win64/cleanup.sh
docker/win64/run.sh
docker/win64/shell.sh
test.sh
test/server/httpf.py

Hello rkd77,
I'm providing several updates to the elinks build system.
In the trying to resolution of this issue:
https://github.com/rkd77/elinks/issues/154
it took ages to compile win64 binary in qemu. So I decided
to create separate docker environment for faster build.
I do provide http server. There are several already in the
test/server directory. But this serves the test directory as
web page and allows browsing the test files.
Thank You in case You'd merge this and feel free to provide feedback

[ build ] win64 docker env, http server

---

build.sh
doc/cross_debug.txt
src/osdep/osdep.c

Hello rkd77,
it's is quite obvious and well known how to use debugger on linux. But it took me while to realize how to debug win64 curses binary on linux. I'm providing the know how to the community.
Feel free to edit / comment or merge.
Have a nice day

[ doc ] debug elinks win64 on linux

---

build.sh
docker/win64/Dockerfile
src/network/socket.c
src/network/ssl/socket.c
src/osdep/osdep.c
src/osdep/win32/overrides.c

Hello rkd77,
these are the changes mentioned here:
https://github.com/rkd77/elinks/issues/158
I'd like to ask You for development review.
The SOCKET_SHIFT is ugly (in ssl/socket.c) but that's how it was made in overrides.c. I just applied the logic to ssl set fd.
I'm available for Your comments or Your changes.
The binaries 
Thank You & best wishes

[ win64 ] changes for win64 with ssl in docker

---

docker/win32/run.sh
docker/win64/run.sh

Hello rkd77,
I'm offering a tiny patch for mounting host file-system to docker guest.
Thank You & take care & best regards

[ win ] mounting tmp to docker guest

---

src/util/error.c

This was deemed bad behavior on the FreeBSD ports list

Remove "user torturation" code

---

src/document/html/parser/general.c
src/document/html/parser/stack.c
src/ecmascript/ecmascript.h

Closes: https://github.com/rkd77/elinks/issues/204
Signed-off-by: Sam James <sam@gentoo.org>

Fix build failures with mujs

---

po/sr.po

Serbian translation updated after `make update-po` with the latest commit on master branch

po/sr.po: Update translation

---

src/ecmascript/Makefile
src/ecmascript/ecmascript-c.c

generate fetch.h from make

---

src/intl/gettext/localcharset.c
src/intl/gettext/plural.c

hi
I'm getting compilation failures for these two sources due to left over ELOG
This pull request fixes things for me

More ELOG fixes
