rkd77/elinks

src/config/options.inc
src/document/document.c
src/document/options.c
src/document/options.h
src/viewer/text/link.c

The color is controlled by
document.browse.links.active_link.insert_mode_colors.background
document.browse.links.active_link.insert_mode_colors.text
Also avoid overloading local variable "i" in get_current_link().

Provide different color for text areas in insert mode.

---

src/viewer/text/link.c

They already have underscores, so underlining them is redundant (and looks a
bit strange).

Avoid underlining active text areas.

---

src/config/actions-main.inc
src/config/kbdbind.c
src/config/options.inc
src/document/html/parser.c
src/document/html/parser/forms.c
src/document/html/parser/general.c
src/document/html/renderer.c
src/document/options.c
src/document/options.h
src/document/plain/renderer.c
src/viewer/action.c

Option document.browse.preferred_document_width controls the
width of the document, so that documents are rendered with narrower
width than screen width.  Makes it easier to read paragraphs.
Patch originally from Shalon Wood <dstar@pele.cx>, see bug #1063.
Instead of using max_document_width as the hard limit to the document
width, it uses a soft limit, where if the document does not fit (due to
tables, etc.), then larger width is used.  This reduces the need for
horizontal scrolling for wide documents.
Also added toggle-document-width action to toggle between preferred
width and full screen width.  This is bound to 'M' by default.  Initial
toggle status is determined by document.browse.use_preferred_document_width
option.
During dumps, document.dump.width option is still used.  Perhaps …

Add preferred_document_width option.

---

src/config/options.inc
src/document/html/parser.c
src/document/html/parser.h
src/document/html/renderer.c
src/document/options.c
src/document/options.h

These settings are specified by
document.colors.link_number
document.colors.use_link_number_color
The latter setting determines whether the color is used when document
colors are being used.
See bug #1050.

Allow link number colors to be changed.

---

src/bfu/leds.c

This is necessary because the status leds overwrite the possibly very long status_bar, which might break double-width characters. An alternative would be to shorten the status_bar according to the length of the status leds.

Fix broken double-width chars when displaying status leds

---

src/viewer/text/search.c

If doc_view->document->number_of_search_points is 0, move_search_number
crashes at:
pt = doc_view->document->search_points;
x = pt[number].x;
y = pt[number].y;
so it is not sufficient to make find_first_search_in_view return
immediately in this case, move_search_do should return immediately.

Move check on number of search points to move_search_do

---

src/viewer/text/search.c

This commit solves the out-of-memory issue in #21.
It does it by making get_srch() only add the characters in the box of each node to add_srch_chr(), instead of everything from the start of the node to the end of the document. The data structure created this way may be very large, since it contains the characters in the document replicated many times.
This commit reverts the change in this function by 7a006b6dd21b12fb47b3c968d309a3c99e1117e1.

when searching in a node, only search within its box

---

src/config/cmdline.c
src/session/session.c
src/session/session.h
src/viewer/text/search.c
src/viewer/text/search.h

This commit add the remote command search(string) for searching a string in the document. Passing no string is equivalent to searching for the empty string, that is, clears the selection of the previously found string, if any.

add -remote 'search(string)'

---

doc/man/man1/elinks.1.in
doc/remote.txt

This commit documents my previous PR.
I updated remote.txt and the man page. I guess these are the only two places where to document. There is no online help for the specific commands that can be passed via -remote, is there?

document the -remote search(string) function

---

src/cookies/cookies.c

The code in cookies.c would arrange that c->path would always contain
a string ending in "/".  This may have been an attempt to make it
easier to do a proper subpath check in is_path_prefix.
Howver, the overall result is wrong in the case
Set-Cookie: ....;path=/some/thing
and then later
http://site.example.com/some/thing
c->path gets set to "/some/thing/" which doesn't pass the test in
is_path_prefix.
The precise required algorithm is described in RFC6265 5.1.4.  The
existing code fails to implement the first of the three bulleted
conditions at the end of 5.1.4.
The trailing "/" is actually not so helpful for this.  It is more
convenient to change is_path_prefix to do subpath matching directly:
we change it to insist that the supposed path prefix is a textual
prefix of the request path, …

cookies: Properly handle cookie path= equal to request path

---

src/config/options.inc
src/terminal/mouse.c

Disabling mouse support is useful if one does not want to use the mouse for the elinks UI but prefers gpm selection to be possible without pressing ctrl. Yet, mouse support can only be disabled at compile time, which means that if one uses elinks from a distribution this is not possible.
This merge request introduces a config variable for disabling the mouse.
In order for selection to be possible without pressing control, mouse initialization has to be skipped altogther. The change is relatively small if disabling or enabling the mouse only takes place at the next restart of elinks. Otherwise, there should be a mechanism for initializing or closing the mouse at
runtime. I don't know if this is worth the effort.

config option for disabling the mouse

---

src/viewer/text/search.c

elinks used to signal when the search string was not found in the document. This commit restores that behaviour, in almost the same way it was done before.
This change unveiled another problem: function ``move_search_do()`` returns an ``enum frame_event_status``, but this return value is then returned as is by the calling function ``get_searched_all()``, which however returns an ``enum find_error``.
This is the reason why I had to check ``error == FIND_ERROR_NOT_FOUND``, which wasn't in the original elinks code and shouldn't be necessary.

show an alert when the search string is not found

---

doc/man/man5/elinks.conf.5
src/network/ssl/ssl.c
src/protocol/uri.c

As most websites now use https making an initial http request for every url path you type is slow and insecure.

Let requests default to https

---

doc/mime.txt
src/mime/backend/default.c
src/session/download.c

Most if not all browsers allow viewing an image by itself. When they do, they show the image url in the address bar. The corresponding operation in elinks   is to open the image with an external handler. Many image viewers show or let the user show the image name, but this is the name of the temporary file elinks downloaded the image to, not the uri. Some image viewers accept an   image title to be shown instead or in addition to the file name: feh has the --info option, gwenview has --title, fbv has -n. Passing the image uri makes them produce the expected behaviour.
This commit changes the format of the handler string: %u stands for the uri, in addition to %f for the local file name. The old syntax is still accepted since % followed by space or the end of the string is replaced by the …

also pass the uri as %u to external handlers

---

src/scripting/ruby/core.h

Fixes the errors
x86_64-pc-linux-gnu-ld: hooks.o:(.bss+0x0): multiple definition of `erb_module'; core.o:(.bss+0x0): first defined here
x86_64-pc-linux-gnu-ld: ruby.o:(.bss+0x0): multiple definition of `erb_module'; core.o:(.bss+0x0): first defined here
Bug: https://bugs.gentoo.org/730658

Fix compilation with gcc-10

---

src/mime/backend/mailcap.c
src/session/download.c

The "what do to?" dialog uses %f and %u, so better have that shown to the user.

update the "What to do?" dialog to the new format with %f for the file

---

src/dialogs/download.c

Downloading of large data: uri was slow. This commit is a quick fix to that.
Whether "downloading" of data: uri is a real download to be shown in the downloading window is arguable.

do not display downloads of protocol "data:"

---

src/session/download.c

When calling an external viewer, the whole uri replaces %u in the command string. If the uri is of data: scheme, it is not only useless but may also be very long since it encodes the whole content of the image.
This commit truncates it to 40 characters and adds "..." at its end. This is enough to show the data:part, the type and the encoding, which are the only parts that may be of some interest to the user.

truncate data: uri passed to the external viewer

---

src/protocol/uri.c

The default name of the file an image is saved to is the last part of the uri, everything that follows the last slash in it. In case of a data: uri, this results in a random-looking sequence of characters. This commit turns that to "data", possibly followed by the file extension if the mime type is recognized to the be one of the typical ones: jpeg, gif, png, txt or html.
I do not like much the use of the ADD_EXTENSION_FROM_TYPE() macro sequence rather than looking up the default extension from /etc/mimetypes, but is coherent with the similar strategy used in mime/backend/default.c
Here are some testing files: [data.zip](https://github.com/rkd77/felinks/files/5294255/data.zip)

meaningful default save name for data: uri content

---

src/document/document.h
src/ecmascript/spidermonkey.c
src/ecmascript/spidermonkey/document.c
src/ecmascript/spidermonkey/localstorage.c
src/ecmascript/spidermonkey/util.h
src/session/session.c
test/ecmascript/arithmetics.html
test/ecmascript/document_replace.html
test/ecmascript/document_write.html

Hello rdk77,
this is pull request for following:
+ Fixed get property location in spidermonkey document.c
+ Added replace function in spidermonkey document.c
+ Fixed localstorage set item so numeric variable can be passed from js
+ Added function jshandle_value_to_char_string to util.h
+ Added emcascript_counter into document/document.h
+ Changed session/session.c and added rerender after document has been changed in js
+ Added tests for document.replace and document.write(ln)
+ Added helper function document replace of char*
The rerendering is really not 100% nice. But I didn't find any better solution than place it on the session
level. When I tried that from the actual document.replace it was probably called too often and had
some unexpected behavior.
There is a variable …

[smjs document replace] fixed property location, replace and writel

---

src/viewer/text/search.c

Apparently, move_search_number() doesn't get called at all when searching failed. Therefore, the number of search points can only be zero when no previous search was performed.
This made me realize that nothing is shown when pressing 'n' after a failed search. Is this reasonable? It would be a separate issue anyway.

fix error message when no previous search was performed

---

src/viewer/text/search.c

This was way easier than I thought. 
The problem was that pressing 'n' after a failed search shows nothing.

alert when moving to the next match of a failed search

---

src/config/options.inc
src/session/history.c
src/session/history.h
src/viewer/action.c

This commit introduces a new option ui.back_to_exit to close the current tab when going back from its initial page. It also closes elinks if it was the last tab.
This is what happens for example in some Android browser.
It may be useful on a PC is to make elinks work as an html file viewer, where another program calls elinks to show an html file, and the user expects to go back to that other program when going back from the initial page.

optionally, going back from initial page closes tab or elinks

---

config2.h.in
src/osdep/unix/sysinfo.h

Fixes #104.
The problem was with the SIGCHLD that naturally arrives when the child process (the uri passing program) ends. Normally, it interrupts the select in select_loop() in main/select.c, where it does not cause any problem. When the bug occurs, it instead interrupts the read() in in_kbd() in terminal/kbd.c. That causes a call to free_itrm(), which sets program.terminate to 1.
This commit fixes the problem by ignoring a -1 returned by read() if errno is EINTR. I am not sure whether this is appropriate behaviour.
Anyway, the uri passing programs should have a "block terminal" option like the external viewers. This way, elinks could stop reading keyboard during a call to an external program that reads input.

do not exit if SIGCHLD interrupts a read

---

src/osdep/osdep.c
src/osdep/osdep.h
src/terminal/terminal.c

When elinks calls a program with TERM_EXEC_FG, it stops reading from stdin so that the program can do that. But with TERM_EXEC_BG, it does not. Both the program and elinks read from stdin. A keystroke may go to the first or to the second, unpredictably.

close stdin before calling a background program

---

doc/man/man5/elinks.conf.5

As far as I can tell the only part of the documentation about uri passing is the man page of elinks.conf. I cannot find any txt file about it.

document the option for running an external program in the foreground

---

src/osdep/osdep.c
src/osdep/osdep.h
src/session/download.c
src/session/download.h

I am in doubt whether I should duplicate ``name.source`` and call ``done_string(name)`` instead of just returning ``name.source`` in ``tempname()``.
This function creates the file empty and returns the name. This is unavoidable if using one of the suggested replacing functions, since they solve the race condition precisely by creating the file. The other changes are because of this, since the file by that name is now supposed to exist.
There is also a reference to the deprecated ``tempnam()`` in ``lua/core.c`` which is still to be replaced.

avoid use of tempnam

---

doc/lua-scripting.txt

The new version of ``tmpfile()`` creates the file. It is still vulnerable to symlink attacks as the previous one as another user may delete the file and recreate it as a symlink before it is opened for writing.

update documentation of the lua tmpfile() function

---

src/scripting/lua/core.c

Two api methods for lua scripting has been added.
`reload()` allows to refresh the document without triggering a new
html request. This commits expose that existing internal function to the
lua api.
One example where it is useful : making a lua hook that allows to edit a
local file we're browsing and see the change without having to perform a
full reload (thus losing the scrolling position). Or anything else that
allows to interactively modify the currently loaded document.
`goto_url()` allows to navigate to given url long after the page has been
loaded (so follow_url_hooks can't be used).
Example where it's useful : binding a key to load the latest archive.org
snapshot for current page (especially useful when using tor and being
constantly harassed by cloudflare).

[lua] expose reload() and goto_url() to lua api

---

po/sr.po

This PR updates the Serbian translation, converting leftover ASCII-style quotes to UTF-8 and including a few other minor fixes.

po/sr.po: Convert quotes from ASCII to UTF-8; a few minor fixes

---

.gitignore
build_win64.sh
doc/cross_mingw.txt
src/intl/width.c
src/network/dns.c
src/osdep/osdep.c
src/osdep/osdep.h
src/protocol/bittorrent/piececache.c
src/terminal/kbd.c
src/terminal/terminal.c

Hello rkd77,
I would like to provide minimalistic build script for (build_win64.sh).
It was tested on Debian 10 using:
miky@deb:~/dev/work/elinks_win64$ x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 8.3-win32 20190406
It does compile the elinks.exe binary for Windows x64.
I did include simple document to describe the cross-compilation.
Thank You and have a nice day

[ win64 ] build_win64.sh, doc etc.

---

build.sh
docker/win64/Dockerfile
src/network/dns.c
src/network/ssl/socket.c
src/osdep/stub.h

Hello rkd77,
I'm offering this patch that's result of compilation of openssl suport on win64. It does compile but it does have some bugs in the similar manner like the http support on win64 had. 
This patch provides docker configuration for --with-openssl option.
I'm adding several changes to the code. Each my change is defined as preprocessor directive to eliminate impact on other platforms.
There weren't many changes needed for elinks to compile with the openssl support. One thing I'm unsure about is the different between inet_aton and inet_pton. The first (inet_aton) is not provided by openssl compiled on mingw so I just added the directive for WIN32 to use inet_pton.
There is a small difficulty with X509_NAME on win64 because wincrypt.h does redefine it as something completely …

[ win64 ] added openssl build support to docker, minor code changes

---

src/osdep/osdep.c

Hello rkd77,
there is a small change to the:
https://github.com/rkd77/elinks/pull/159
In the current state the master branch does compile on win64 but won't run correctly.
This is a small fix to the pull request 159.
I guess the change to osdep/win32.c has been lost somewhere in the translation.
Thank You & best wishes

[ win64 ] fix socket blocking

---

src/osdep/win32/overrides.c

Hello rkd77,
this is probably better optimized to sleep only when there is nothing to do.
Please review the change and let me know if that's reasonable change.
Thank You & have a nice day

[ win64 ] change in select - sleep only when nothing to do

---

src/session/session.c

Hello rkd77,
some time ago I added rerender for javascript to rerender upon form submit.
It caused core dumps. I'm sending fix. The issue is described here:
https://github.com/rkd77/elinks/issues/171
Thank You & take care
mtatton

[ javascript ] rerender core dumps fix

---

build.sh
configure.ac
docker/lin64/Dockerfile
docker/lin64/build.sh
docker/lin64/cleanup.sh
docker/lin64/run.sh
docker/lin64/shell.sh

Hello rkd77,
I'm offering patch for javascript build. This patch offers:
1] running
$ build.sh build 
- builds automatically the elinks. This is preparement for automatic building elinks in docker for several different platforms without human intervention
2] There is a small change in configuration.ac ... if You don't mind I replace the /usr/lib/libquickjs.a for /usr/local/lib/libquickjs.a The change is because that's the default location for the static library
3] Offering dockerfile for elinks with javascript for linux x64.
Thank You & have a nice day
mtatton

[ build ] lin64 js docker and automatic build

---

configure.ac

configure defines a main function without a return type, leading to a -Wimplicit-int warning (enabled by default in C99 and later dialects). This commit fixes that.
Related to:
https://fedoraproject.org/wiki/Changes/PortingToModernC
https://fedoraproject.org/wiki/Toolchain/PortingToModernC

configure: Fix an "implicit int" warning

---

doc/meson.build

This is more sane than hardcoding 'share/doc/elinks'
Also using join_paths method os better for portability to non-Unix systems

[doc] use join_paths method & datadir config for generating default doc_dir

---

contrib/debian/watch

It would be better to remove this file (or even the whole contrib/debian dir), as it confuses uscan

Fix watch file

---

src/bfu/dialog.c
src/bfu/menu.c
src/document/document.cpp
src/document/plain/renderer.c
src/terminal/screen.c
src/terminal/terminal.cpp
src/terminal/window.c
src/viewer/text/draw.c

hi
this adds a number of trivial conditionals to allow building with libsixel disabled
works for me
For  the ``set_*_term_event()`` calls I have set dummy 0 values when libsixel is disabled: don't know if this is acceptable or needs some more appropriate fix...
thanks
ciao
-g

Allow building with -Dlibsixel=false

---

src/main/object.h
src/protocol/uri.c
src/protocol/uri.h

Perl now includes own `struct object` which clashes with elinks implementation. Renamed `struct object` to `struct elinks_object` to avoid it.
Bug: https://bugs.gentoo.org/909042

Fix compilation with Perl 5.38

---

src/document/gemini/renderer.c

This patch makes paragraphs separated by an empty new line appear after an empty new line when rendered in elinks.
Previously, for a gemtext source that looks like this:
First para
Second line
Second para
It renders like this:
First para
Second line
Second para
After this patch, they now render like this:
First para
Second line
Second para
Unfortunately this also adds a `</p>` to the start of the HTML, as well as a `<p>` at the end, both redundant; but since the HTML is parsed and rendered later on, it does not seem to alter how the document would look.
</p><p> First para <br> Second line </p><p> Second para </p><p>
I could possibly add a `first_paragraph` variable and a `i != buffer->length` check to remove the first `</p>` and last `<p>` in the HTML, making the HTML source "prettier". …

[gemini] Use paragraph tags on gemtext empty lines

---

src/main/interlink.c
src/main/main.c
src/main/main.h
src/osdep/signals.c
src/terminal/terminal.c

After commit b102addf9 following request #287, `term->master` is used as test to see if this is session master process we want to wakeup with SIGCONT after suspend (master must be kept running, or other slaves will block).  Test uses comparison `term->fdout == 1`, which is never true in the case of forked master when `ui.session.fork_on_start`.  The forked master has different (>10) fdout descriptor numbers, so it will never be `term->master` and thus `master_pid` will still have its initialized value 0.
Instead we can get the pid directly after forking, and use the interlink creation attempt to decide whether this is a master or slave process depending on successful connect().  This was tested with both `fork_on_start=1` and `fork_on_start=0` with different suspend/resume permutations …

fix suspend in session master when fork_on_start

---

src/main/interlink.c

In [a previous issue](https://github.com/rkd77/elinks/issues/287#issuecomment-1984869268) it was noted that the first elinks session has a long startup delay of ~350ms, whereas slaves start instantly.  A workaround is to use `dtach` for the first session, and leave it headless, so all subsequent `elinks` are slaves.
It was [pointed out](https://github.com/rkd77/elinks/issues/287#issuecomment-1983532712) that `ui.sessions.fork_on_start` already was designed for this purpose.  However, even in that case, the first-session delay still remains.
After instrumenting key sites in `main.c` and `interlink.c` following the call path `init()` -> `init_interlink()` -> `connect_to_af_unix()` like so:
``` c
struct timeval tstart, tlast;
void
print_elapsed(const char *whence)
{
struct timeval tnow, …
```

remove 300ms startup delay and optimize fork_on_start

---

doc/tools/keys2doc

\| is an incompatible GNU extension to BREs.  This corrupts formatting of the elinkskeys(5) man page on any system where sed is not GNU sed (e.g. the BSDs).  Use ERE syntax instead.

Eliminate sed(1) GNUism

---

src/cache/cache.c
src/document/libdom/css.c
src/formhist/formhist.c
src/protocol/data.c
src/protocol/http/http.c
src/util/base64.c

Compiles with zero warnings and errors using:
```sh
gcc version 14.2.1 20240921 (Gentoo 14.2.1_p20240921 p5)
GNU assembler version 2.43.1 (x86_64-pc-linux-gnu) using BFD version (Gentoo 2.43 p2) 2.43.1
```

silence signedness warnings and errors

---

docker/alpine-static/Dockerfile

Alpine Linux moved the .a file from the c-ares-static subpackage to the origin c-ares. As c-ares-dev depends on c-ares, we can just drop the c-ares-static dependency.
Ref: https://gitlab.alpinelinux.org/alpine/aports/-/commit/400607034d000fcf84ca2d3ed6a00a69429aee2d

[docker] update dependencies

---

meson.build

When it was false, meson complained that it shouldn't be a boolean value, see: https://salsa.debian.org/aelmahmoudy/elinks/-/jobs/6836245/raw

Fix default value for libdomdeps to empty list instead of false

---

src/protocol/curl/sftp.h

fixes compilation error when sftp is enabled but ftp is disabled

[sftp] add declaration of ftp_curl_handle_error

---

src/scripting/ruby/core.c
src/scripting/ruby/ruby.c

When trying to update the version package for openSUSE the build is faling due to missing `ruby/version.h` not being included correctly. This fix the building process.

Inlcude the ruby/version.h in ruby.c since it was moved
